### ISSUE TITLE
When I remove try catche

### ISSUE THREAD

**Issue by hustcc** [getsentry/raven-java-examples#5]
When I rm `try catch`, code below:

```java
package com.getsentry.example;

import org.apache.log4j.Logger;

public class Application
{
    private static final Logger logger = Logger.getLogger("Application");

    public static void main(String[] args)
    {
        // try {
            int example = 12 / 0;
        // } catch (Exception e) {
            // logger.error("Caught exception!");
        // }
    }
}
```

then mvn compile error.

```
[com.getsentry.example.Application.main()] INFO com.getsentry.raven.DefaultRavenFactory - Using an HTTP connection to Sentry.
[WARNING]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 10
        at com.getsentry.example.Application.main(Application.java:12)
        ... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.724 s
[INFO] Finished at: 2016-08-05T23:06:36+08:00
[INFO] Final Memory: 13M/105M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java (default-cli) on project raven-java-log4j-example: An exception occured while executing the Java class. null: InvocationTargetException: 10 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[Thread-1] INFO com.getsentry.raven.connection.AsyncConnection - Automatic shutd
own of the async connection
[Thread-1] INFO com.getsentry.raven.connection.AsyncConnection - Gracefully shutdown sentry threads.
[Thread-1] INFO com.getsentry.raven.connection.AsyncConnection - Shutdown finished.
```

How to do with it ?

**Comment by bretthoerner** [comment]
Discussing here: https://github.com/getsentry/raven-java/issues/241
